### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by nunomaduro** [pestphp/drift#32]
Hey friends, Can you tell me how to run tests in drift? They seem to be failing in my machine.

**Comment by owenvoke** [comment]
I think I was just running `vendor/bin/phpunit` and it worked. 🤔 I guess we should probably add a Composer script for that?

**Comment by owenvoke** [comment]
Oh, I see what you mean... all the tests are failing at the moment. 😬 I think that's because of Rector dependencies. 🤔 I was hoping we could use `rector/rector-prefixed` with a specific version to prevent these types of issues happening in future, but it looks like that won't work because the classes aren't found.

Anyway, Rector v0.7.66 should resolve this as afaik (`dev-master` at the moment). 🤷🏻 I've opened #35 to show this. 👍🏻

**Comment by owenvoke** [comment]
Think this can be closed, tests are run using `composer test` now. 👍🏻
